### PR TITLE
Add nix build code and build against aeson 1.4.6.0

### LINKED ISSUE #11: Add Nix code for building
Now that we require newer Aeson versions, aeson-commit doesn't build cleanly on nix. Add nix code to handle getting the correct versions of Aeson and its dependencies

### PR DESCRIPTION
**Pull request by rprije**
Adds nix code for building against season 1.4.6.0. Resolves #11.

### CODE REVIEW

**Comment by considerate** [comment]
What's the reason for not using `haskell.nix` here?

**Comment by rprije** [comment]
No good reason except it was quicker and easier and I wanted to decouple the job of getting it to build from the larger job of getting aeson-commit into a more standardised state with proper stack project code, documentation, buildkite etc. Doing it properly is starting to feel like it needs a more general solution for making a standard repo build skeleton the simplest default for all our projects rather the current state which seems to involve a lot of setup work for each new project.

**Comment by cdepillabout** [comment]
Maybe we can talk about what to do about this at the weekly meeting on Wednesday.

I agree that moving this to `haskell.nix` would probably be the best solution, but we don't currently have a good skeleton for how to setup `haskell.nix`, `stack.yaml`, buildkite, etc.  It would be great to have something like this, especially since now we've split off aeson-commit, weave, caffe2-haskell, etc.

Although I don't expect us to continue making major improvements to `aeson-commit`, so maybe just using the normal nixpkgs haskell stuff is good enough for now for aeson-commit.  Although if we go this route we should definitely pin nixpkgs for reproducibility.

**Comment by rprije** [comment]
I created xc-jp/nix#1 before seeing your comment, @cdepillabout . I'll hold off on going any further with it before we've had a chance to discuss it more.

**Comment by considerate** [comment]
Closing, since I think the nix build should be reworked to use `haskell.nix`.

**Pull request closed without merging**
